theme: jekyll-theme-minimal
title: qube
description: A virtual office that enables you to work remotely. See who's chatting with coworkers, out of the office, or stepped out for lunch.
repository: seeq12/qube
logo:  https://raw.githubusercontent.com/seeq12/qube/master/app/assets/images/default/qube.png
